# Generated by Django 3.1.4 on 2021-05-07 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='mileage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999, 'Please enter a number less than 1000000')]),
        ),
        migrations.AlterField(
            model_name='auto',
            name='nickname',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2, 'Please enter a nickname with 2 or more characters')]),
        ),
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2, 'Please enter a name with 2 or more characters')]),
        ),
    ]
