# Generated by Django 3.1.4 on 2021-05-07 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999, 'Please enter a number less than 10000')]),
        ),
    ]
